//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappinessSurvey.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submitsurvey
    {
        public int ss_id { get; set; }
        public int sq_id { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
        public int s_id { get; set; }
        public int u_id { get; set; }
        public int role_id { get; set; }
    
        public virtual roletbl roletbl { get; set; }
        public virtual surveyquestion surveyquestion { get; set; }
        public virtual surveytbl surveytbl { get; set; }
        public virtual UserTbl UserTbl { get; set; }
    }
}
