//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappinessSurvey.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class surveyquestion
    {
        public int sq_id { get; set; }
        public int sur_id { get; set; }
        public int q_id { get; set; }
    
        public virtual questiontbl questiontbl { get; set; }
    }
}
